### ISSUE TITLE
Do not reset build cache on every rerun

### ISSUE THREAD

**Issue by back2dos** [haxetink/tink_macro#10]
May be the cause of https://github.com/HaxeFoundation/haxe/issues/5735

**Comment by back2dos** [comment]
@kevinresol Can you please check if this makes your memory issue any better?

**Comment by back2dos** [comment]
Forget what I just said. It seems I forgot to actually use the cache in tink_json ... sorry :D

**Comment by kevinresol** [comment]
I dunno, because I was working with the rethinkdb driver recently and I didn't use *any* macro there, but the haxe completion server (for vscode) still eats up memory like a beast and renders my machine totally unresponsive often.
I have totally no clue.

**Comment by back2dos** [comment]
Ok, now the parsers are actually cached. When you continue that work, please let me know if it got better?
