### ISSUE TITLE
haxelib.json URL is broken

### ISSUE THREAD

**Issue by Gama11** [haxetink/tink_macro#23]
The URL on http://lib.haxe.org/p/tink_macro/ doesn't seem to work anymore. Not sure what the replacement is / if there is one, so I didn't submit a PR. :)

http://haxetink.org/tink_macro

**Comment by kevinresol** [comment]
Looks like we either need to change the URL in haxelib.json or add the gh-page branch. (And multiply the work by 50 for all the tink libs 🎉)

**Comment by kevinresol** [comment]
I think pointing `http://haxetink.org/*` to `https://github.com/haxetink/*` is the easiest solution. We have the documentation link in the github repo already anyway.
