### ISSUE TITLE
TypeMap can't distinguish anon type with field meta

### ISSUE THREAD

**Issue by kevinresol** [haxetink/tink_macro#25]
The following code illustrate the issue:
```haxe
class Main {
  static function main() {
    var a = tink.Json.parse(('{"a":1}':A));
    trace(a);
    var b = tink.Json.parse(('{"b":1}':B)); // using the same parser as A and fails at runtime
    trace(b);
  }
}

typedef A = {@:json('a') var foo:Int;}
typedef B = {@:json('b') var foo:Int;}
```

**Comment by kevinresol** [comment]
Tried to perform some deep comparison but there will be recursion problem for types like:

```
typedef Rec = {v:Rec}
```

**Comment by kevinresol** [comment]
I wonder how the compiler figure out these two types to be the same:

```haxe
typedef R1 = {x:R1};
typedef R2 = {x:R2};
```

**Comment by back2dos** [comment]
Essentially, we can now pass any normalizer to the `TypeMap` / `BuildCache`. Still need to figure out what's best for each particular lib though ^^
