### ISSUE TITLE
using tink.MacroAPI;

### ISSUE THREAD

**Issue by benmerckx** [haxetink/tink_macro#5]
The readme says to use `using tink.MacroAPI;` but it should be `using tink.MacroApi;` (API => Api)
The former results in `Module tink.MacroAPI is loaded with a different case than tink.MacroApi`
I tried to create a pull request, but my editor is formatting stuff it shouldn't :)

**Comment by back2dos** [comment]
Hehe, ok. Thanks for reporting :)
